### ISSUE TITLE
Create tpuq

### ISSUE THREAD

**Issue by Vardan9898** [Vardan9898/tpuq-project#1]

**Comment by armen9494** [comment]
- [x]  Top navbar different visual styles on different pages

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/49522440/156761483-2a701ef5-98c2-47e4-96e6-fafd85d461b0.png">
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/49522440/156761504-34c9b8a4-6b9f-441f-a9da-d0b0fee91705.png">

**Comment by armen9494** [comment]
- [x] Description must accept normal text size. I have inserted this text and received an error.


Տրամադրվում է օրավարձով և ժամավարձով բնակարան Մաշտոց Ամիրյան փողոցների խաչմերուկում։ Բնակարանն ապահովված է կոմունալ բոլոր հարմարություններով` Օդորակիչ, Wi-Fi, TV ալիքներ, տեխնիկա։
Մոտակայքում գտնվող վայրեր
Հանրապետության հրապարակ
0.7 կմ
Օպերայի թատրոն
0.9 կմ
Սիրահարների այգի
1.1 կմ
Մարշալ Բաղրամեան մետրո կայարան
1.2 կմ
Վերնիսաժ
1.3 կմ
Կասկադ
1.3 կմ
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/49522440/156762088-9b628ce5-c597-45ed-8647-08ffeebb5963.png">

**Comment by armen9494** [comment]
- [x] I'm updating this checkbox disabled, but it's storing as enabled
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/49522440/156764076-0498620b-61f2-4dec-83a6-9b8f2592fe19.png">

**Comment by armen9494** [comment]
- [x] Getting database error on big numbers. Instead of this it must give a validation error.

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/49522440/157004429-86cf3e7a-b277-4cc5-bad4-287484372eff.png">
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/49522440/157004404-053d6094-9566-4832-afc7-aa1e10210437.png">

**Comment by armen9494** [comment]
- [x] Image not showing
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/49522440/157691949-35b55456-96dc-4e33-8516-76981820285b.png">
